name = input("what is your name ")
print("hello," + name)
birth_year = prompt1=input("when was your birthyear? ")
age = 2022 - int(birth_year)
animal = input("whats your favorite animal? ")
print("your username is..")
user = str(name) + str(animal) + str(age)
print(user)
print("-amin")